### ISSUE TITLE
Extension CPLEX: Problem with fixed variables

### ISSUE THREAD

**Issue by fueralles** [optimatika/ojAlgo-extensions#1]
Consider this example:

ExpressionsBasedModel test = new ExpressionsBasedModel();
test.addVariable(Variable.make("1").level(0.5));
test.addVariable(Variable.make("2").lower(0).upper(5).weight(2));
test.addVariable(Variable.make("3").lower(0).upper(1).weight(1));
Expression expressions= test.addExpression("1").lower(0).upper(2);
expressions.set(1, 1).set(2, 1);
test.addIntegration(SolverCPLEX.INTEGRATION);
Optimisation.Result result= test.minimise();

By not submitting the fixed variables, an error is caused (SolverCPLEX.java:251). If variables completely compensated they have to be excluded in that loop. Instead the value of the fixed variable has to be set here. At least I did it for a "dirty" hack.

**Comment by apete** [comment]
Yes, looked like the implementation was half way between using all variables or just the free. See invite works better now.

**Comment by apete** [comment]
Did the changes I made fix the problem? If so, then please close this Issue.

**Comment by fueralles** [comment]
Thank you for the fix and excuse me for the late response. I finally merged it with my version and I did a few tests with your pure version. So far it seems to work well.
