### ISSUE TITLE
Problem with compensate function

### ISSUE THREAD

**Issue by fueralles** [optimatika/ojAlgo-extensions#3]
Hi, 
A problem arose with fixed variables and the compensate function. It seems that fixed variables are eliminated but not influencing the expression boundaries.

`ExpressionsBasedModel test = new ExpressionsBasedModel();
    	test.addVariable(Variable.make("X1").lower(0).upper(5).weight(1));
    	test.addVariable(Variable.make("X2").lower(0).upper(5).weight(1));
    	test.addVariable(Variable.make("X3").level(4).weight(1));
    	Expression expressions= test.addExpression("1").upper(5);
		expressions.set(0, 1).set(1, 1).set(2, 1);
    	test.addIntegration(SolverCPLEX.INTEGRATION);
    	Optimisation.Result result= test.maximise();
    	BasicLogger.debug(result);`

Output: OPTIMAL 6.0 @ [1.0, 1.0, 4.0]

Best regards

**Comment by apete** [comment]
I had mistakenly used peek() rather than map() in a stream. "compensating" should work now.

**Comment by fueralles** [comment]
Yes, now it is working fine. Thanks.
