### ISSUE TITLE
Cplex solver specific options

### ISSUE THREAD

**Issue by fueralles** [optimatika/ojAlgo-extensions#4]
I really appreciate the new feature to set solver specific options without editing the library. However, the subclass "configure" method is never called because of the constructor call in line 75.

**Comment by apete** [comment]
Didn't quite think that through... I'm working on an alternative design.

**Comment by apete** [comment]
Now there is a solution that works.

I've modified ojAlgo to enable this new feature.

When you construct your ExpressionsBasedModel you may call ```theModel.options.setConfigurator(...)```. If you set that to an instance of SolverCPLEX.Configurator it be used/called by the SolverCPLEX just before executing the solver.

**Comment by fueralles** [comment]
I've suspected that a redesign of ojAlgo is required. The new design is working well now. 

It is a great improvement to set the settings now directly without editing the extension file.
