### ISSUE TITLE
Issue with the validate function of ojAlgo

### ISSUE THREAD

**Issue by fueralles** [optimatika/ojAlgo-extensions#5]
If I validate my results from external solver sometimes some constraints are violated. The violation is very small. So far I could check it, the validate function is compted with a higher percision than some solvers. Maybe a threshold for the validation check would be a good idea for these extensions.

**Comment by apete** [comment]
There are several alternative validate methods - I hardly remember what they do - some let you specify the solution to validate and a validation context to control the accuracy requirement.

The option `model.options.solution` control rounding when solutions are copied from the solvers to the model's variable instances. Try changing that.

I recently modified some aspects of how validation works and which options are available.

Change your decency to use the latest ojAlgo snapshot, and experiment with the different alternatives.

**Comment by fueralles** [comment]
Usually I only test the status of an optimization but I tried out the validation function and run into this issue. Probably I just use the options in the wrong way or overlook something. Thus a short example:

`lpModel = new ExpressionsBasedModel();`
`lpModel.options.solution = new NumberContext(12, 15);`
`lpModel.options.feasibility = new NumberContext(12, 15);`
`...`
`lpResult = lpModel.minimise();`
`lpModel.validate(lpResult, new NumberContext(12, 15), BasicLogger.DEBUG);`

In the validate function (Expression.class) there is the call of `context.isDifferent(tmpLimit.doubleValue(), value.doubleValue())` in the if statement. I would have expected that the call looks like `context.isDifferent(context.enforce(tmpLimit), context.enforce(value))`. 

From debugging it seems that the evaluation of expressions with more than one variable is not converted to the the scale in any NumberContext object. If there are some rounded variables (values copied from solution with model.options.solution) in the expression, the error sum can exceed the myZeroError from the NumberContext object in the validate function. 
Alternatively, if I reduce the scale (NumberContext in the validate function) compared to the scale (model.options.solution), I can avoid an invalidity. However, if the lower or upper limits (tmpValue) are more precise than the solution(value-model.options.solution), I run into a new invalidity.

**Comment by apete** [comment]
I'll review the validation code.

For now the best option is probably to just try to tweak the `lpModel.options.solution` parameter.

**Comment by fueralles** [comment]
Thank you. As I mentioned, it is enough to check the solver status for me at the moment. I've just tested the validation function for the possible use of numerical issues. Tweaking the parameters were unsuccessfull. (Enforcing the values works well but it doesn't seems to be a well design.

**Comment by apete** [comment]
I have reviewed the validation code. I did make some minor changes but essentially it was implemented the way I expected it to be.

When you validate you should supply a validation context, and `new NumberContext(12, 15)` is most likely much too strict. The default validation context is `12, 8`. If that doesn't work you have to move to something "less".
